version: "2"

services:
  test:
    image: bash:5
    working_dir: /root/workspace/gitfile/
    volumes:
      - ~/.ssh/:/root/.ssh/
      - ./:/root/workspace/gitfile/
    command:
      - bash
      - -c
      - "apk update > /dev/null 2>&1 && apk add git openssh-client make > /dev/null 2>&1 && make install && gitfile -f ./.gitfile"
